- name: Install Metrorec Service
  hosts: web03
  tasks: 
    - name: Clone a Repository
      git: 
        repo: https://github.com/developer-mide/presento.git
        clone: yes
        update: yes
        dest: /home/ubuntu
      shell: cp /opt/sgc/metrorec/metroclean.service /etc/systemd/system  && cp /opt/sgc/metrorec/metrorec.service /etc/systemd/system
