- name: Install Metro Services
  hosts: web03 #change to host alias or IP address
  become: yes
  tasks:
    - name: Clone a Repository
      git:
        repo: https://github.com/developer-mide/ansible-project.git # use SSH to connect to private repo 
        dest: /opt/sgc
        clone: yes
        update: yes
    - name: Move to systemd folder
      shell: cp /opt/sgc/metrorec/metroclean.service /etc/systemd/system  && cp /opt/sgc/metrorec/metrorec.service /etc/systemd/system
    - name: Start Metrorec Service
      systemd:
        name: metrorec
        daemon_reload: yes
        state: started
        enabled: yes
    - name: start metroclean service
      systemd:
        name: metroclean
        daemon_reload: yes
        state: started
        enabled: yes
