# This file is auto-generated by build_all.sh using bufferchannels.h
# Nevertheless, it is also under version control for convenience.
channel_names = {
	# Channels of general interest. TODO: generic "seqnr" and "monotime" good enough for testing?
	"ade9000_generic_seqnr_32ksps_f32"       : 0,   	# Generic Sequence Number of the sample (currently as received by microcontroller)
	"ade9000_generic_monotime_32ksps_f32"    : 2,   	# Generic Monotonic receive time (currently metrology microcontroller uptime), in uS
	"ade9000_voltage_primary_32ksps_f32"    : 11,   	# Primary   voltage (usually 240 V for split-phase), calibrated
	"ade9000_voltage_secondary_32ksps_f32"  : 12,   	# Secondary voltage (usually 120 V for split-phase), calibrated
	"ade9000_current_phaseA_32ksps_f32"     : 14,   	# Current on leg "A", calibrated - not phase-shift compensated to voltage!
	"ade9000_current_phaseB_32ksps_f32"     : 15,   	# Current on leg "B", calibrated - not phase-shift compensated to voltage!
	# Channels which are usually only used by developers as well as calibration & verification tools, they could change frequently:
	"ade9000_buffer_seqnr_32ksps_i32"       : 90,   	# Sequence number of the sample, as received by metrorec
	"ade9000_udp_seqnr_32ksps_i32"          : 80,   	# 
	"ade9000_cur_wfb_index_32ksps_i32"      : 81,   	# 
	"ade9000_loc_wfb_index_32ksps_i32"      : 82,   	# 
	"ade9000_discovery_time_32ksps_i32"     : 83,   	# 
	"ade9000_sample_seqnr_32ksps_i32"       : 91,   	# Sequence number of the sample, as recorded by frontend (e.g., metrology microcontroller)
	"ade9000_buffer_monotime_32ksps_i32"    : 92,   	# Monotonic receive time at metrorec (usually jetson uptime), IN NANOSECONDS (int32 wraps about every second)
	"ade9000_sample_monotime_32ksps_i32"    : 93,   	# Monotonic receive time at frontend (usually metrology microcontroller uptime), IN NANOSECONDS (int32 wraps about every second)
	"ade9000_voltraw_primary_32ksps_i32"    : 21,   	# raw 24-bit data for ade9000_voltage_primary_32ksps
	"ade9000_voltraw_secondary_32ksps_i32"  : 22,   	# raw 24-bit data for ade9000_voltage_secondary_32ksps
	"ade9000_voltraw_tertiary_32ksps_i32"   : 23,   	# raw 24-bit data for ade9000 voltage channel C
	"ade9000_voltraw_metastuff_32ksps_i32"  : 24,   	# raw 24-bit data for ade9000 voltage channel EMPTY (reserved for meta stuff in TEENSPI)
	"ade9000_curraw_phaseA_32ksps_i32"      : 25,   	# raw 24-bit data for ade9000_current_phaseA_32ksps
	"ade9000_curraw_phaseB_32ksps_i32"      : 26,   	# raw 24-bit data for ade9000_current_phaseB_32ksps
	"ade9000_curraw_phaseC_32ksps_i32"      : 27,   	# raw 24-bit data for ade9000 current channel C
	"ade9000_curraw_phaseN_32ksps_i32"      : 28,   	# raw 24-bit data for ade9000 current channel N
}
